mex -v CXXFLAGS="\$CXXFLAGS -Wall -Wno-sign-compare" ...
    -I/Users/jack/src/ceres-solver/include/ -I/usr/local/include/eigen3/ ...
    -L/Users/jack/src/ceres-solver/release/lib/ -lceres_shared ...
    -lcholmod -lamd -lcolamd -lcxsparse -lprotobuf -lglog ...
    refine_corrective_triple_nonlinear_mex.cpp ...
    unit-vector-parameterization.cpp chain.cpp

mex -v CXXFLAGS="\$CXXFLAGS -Wall -Wno-sign-compare" ...
    -I/Users/jack/src/ceres-solver/include/ -I/usr/local/include/eigen3/ ...
    -L/Users/jack/src/ceres-solver/release/lib/ -lceres_shared ...
    -lcholmod -lamd -lcolamd -lcxsparse -lprotobuf -lglog ...
    nrsfm_low_rank_nonlinear_mex.cpp low-rank-nrsfm.cpp chain.cpp

mex -v CXXFLAGS="\$CXXFLAGS -Wall -Wno-sign-compare" ...
    -I/Users/jack/src/ceres-solver/include/ -I/usr/local/include/eigen3/ ...
    -L/Users/jack/src/ceres-solver/release/lib/ -lceres_shared ...
    -lcholmod -lamd -lcolamd -lcxsparse -lprotobuf -lglog ...
    find_structure_low_rank_nonlinear_mex.cpp low-rank-nrsfm.cpp chain.cpp

mex -v CXXFLAGS="\$CXXFLAGS -Wall -Wno-sign-compare" ...
    -I/Users/jack/src/ceres-solver/include/ -I/usr/local/include/eigen3/ ...
    -L/Users/jack/src/ceres-solver/release/lib/ -lceres_shared ...
    -lcholmod -lamd -lcolamd -lcxsparse -lprotobuf -lglog ...
    find_structure_approx_low_rank_nonlinear_mex.cpp low-rank-nrsfm.cpp chain.cpp
