mex -v CXXFLAGS="\$CXXFLAGS -Wall -Wno-sign-compare" ...
    -I/Users/jack/src/ceres-solver/include/ -I/usr/local/include/eigen3/ ...
    -L/Users/jack/src/ceres-solver/release/lib/ -lceres ...
    -lcholmod -lamd -lcolamd -lcxsparse -lprotobuf -lglog ...
    nrsfm_nonlinear_mex.cpp chain.cpp
